#PROD
# version: '3'
# services:
#   angular-frontend:
#     container_name: talkvera-ui-container 
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - '4200:80'

#DEV
version: '3'
services:
  angular-frontend:
    container_name: talkvera-ui-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

